### ISSUE TITLE
Support for Splunk Cloud

### ISSUE THREAD

**Issue by ericluria** [splunk/terraform-provider-splunk#12]
I see in [the provider](https://github.com/splunk/terraform-provider-splunk/blob/5e5f936bf4091e0018928ac90d79b72259473272/splunk/provider.go#L36-L47) that authentication is done with username/password, however Splunk Cloud uses tokens for REST API authentication.

Are there plans to support Splunk Cloud with this terraform module using token authentication?

**Comment by anushjay** [comment]
@ericluria Currently the provider only supports Splunk Enterprise. We are looking into Splunk Cloud but don't have any concrete plans yet.
https://docs.splunk.com/Documentation/SplunkCloud/6.5.0/User/RESTAPIaccess
What type of Splunk Cloud are you using ->

**Comment by ericluria** [comment]
@anushjay thank you for the quick response! We're on the latest version of (managed) Splunk Cloud, which supports token authentication for the REST API. We use SAML for login so I don't think we can use username/password for API authentication, though.

**Comment by anushjay** [comment]
@ericluria Understand. Thanks for bringing this up. We have a PR for supporting auth token authentication (https://github.com/splunk/terraform-provider-splunk/pull/13) and will merge it after reviews.

**Comment by ericluria** [comment]
@anushjay that's awesome, thanks for the quick turnaround! I'm also happy to test it out and see if it works on my end.

**Comment by anushjay** [comment]
@ericluria We just pushed `v1.2.0`. In the new version, there is an option to provide `auth_token` as part of the provider configuration. Please try it out and let us know if it works as expected for you.

**Comment by jjm** [comment]
I can confirm that the `auth_token` provider functions for REST API authentication against Splunk Cloud, however it's not really clear which resources are usable against Splunk Cloud from Terraform

So far in my testing so I've found that the following resources complete (and can be seen in Splunk Cloud WebUI):

- splunk_authorization_roles
- splunk_admin_saml_groups
- splunk_authorization_roles
- splunk_authentication_users

At least the following resources are not supported on Splunk Cloud (error about missing role(s), as I've only the `sc_admin` role), so far I've not cross referenced resources against [Access requirements and limitations for the Splunk Cloud REST API](https://docs.splunk.com/Documentation/Splunk/8.1.0/RESTTUT/RESTandCloud) yet:

- splunk_inputs_http_event_collector
- splunk_inputs_tcp_splunk_tcp_token

Also while `splunk_indexes` resource completes successfully and it's possible to select the index for uploading data into it does not receive data. From some digging I think the likely caused by it not using `/services/cluster_blaster_indexes/sh_indexes_manager` which is where you need to create indexes for Splunk Cloud (this is what I was most insteaded in using this provider to manage).

Being able to do the following:

```hcl
provider "splunk" {
  url        = "example.splunkcloud.com:8089"
  splunk_cloud = true
}
```

And have those resources that are not supported error and there being a new resource for `cluster_blaster_indexes` so that we can manage indexes using the correct REST API endpoint when using splunk cloud would be awesome.

**Comment by anushjay** [comment]
Splunk ideas added for Splunk TF provider to support splunk cloud -> https://ideas.splunk.com/ideas/PLECID-I-195
Please upvote!

**Comment by rastakajakwanna** [comment]
Indexes are also not compatible with Cloud.

Parameters for "home_path" and "cold_path" are mandatory for Cloud.
Terraform provider defines them by default as:
```home_path                        = "$SPLUNK_DB/$_index_name/db"
cold_path                        = "$SPLUNK_DB/$_index_name/colddb"```
That is in line with the requirements for Cloud, but it is somehow not enough for the full propagation. Indexes are then visible for HEC tokens and "auto-filler" can suggest them in Search query, but no data is coming.

**Comment by AzCii** [comment]
I'm also hoping for better support for Splunk Cloud, I also found that splunk_indexes gets created but I don't get data in them and i can't even see them in the Index list in the WebUI.

I have however had good luck so far with using splunk_saved_searches in Splunk Cloud.

**Comment by korenyoni** [comment]
> I'm also hoping for better support for Splunk Cloud, I also found that splunk_indexes gets created but I don't get data in them and i can't even see them in the Index list in the WebUI.

With the `splunk_indexes`, I am also confirming that the index gets created, but I cannot see in the Web UI. Not sure about data ingestion.

There is the `splunk_sh_indexes` resource introduced in #68, but it does not succeed in being created:

```hcl
resource splunk_sh_indexes_manager "account_index" {
  for_each                    = local.account_contexts
  name                        = each.value.account_index_name
  datatype                    = "event"
  frozen_time_period_in_secs  = var.index_frozen_time_period_in_secs
  acl {
    app     = local.acl.app # "system"
    owner   = local.acl.owner # "nobody"
    sharing = local.acl.sharing # "global"
    read    = local.acl.read # ["admin"]
    write   = local.acl.write # ["admin"]
  }
}
```

```
Error: Http Error: [400] 400 Bad Request {"messages": [{"type": "WARN", "text": "Missing required argument \"maxGlobalRawDataSizeMB\""}]}
```

In Splunk Cloud, the following event exists:

```
07-12-2021 18:57:28.540 +0000 WARN  ScriptRestHandler [6450 HttpDedicatedIoThread-7] - Custom REST endpoint at "/servicesNS/nobody/cloud_administration/cluster_blaster_indexes/sh_indexes_manager/[INDEX NAME]?count=-1&output_mode=json" was called by [REDACTED] with request data but no Content-Type: header; not parsing POST arguments
```

Which to me suggests `maxGlobalRawDataSizeMB` was not acknowledged because the provider is not passing the `Content-Type` header expected by Splunk Cloud.

Additionally, I am also confirming that there is an issue with `splunk_inputs_http_event_collector` on Splunk Cloud as well. The `splunk_inputs_http_event_collector` resource is deployed in tandem with `splunk_indexes`. But its creation does not succeed:

```hcl
resource "splunk_inputs_http_event_collector" "hec_token" {
  for_each = local.account_contexts
  name     = each.value.account_index_name
  index    = splunk_indexes.account_index[each.key].name
  indexes  = [splunk_indexes.account_index[each.key].name]
  token    = random_uuid.hec_token[each.key].result
  acl {
    app     = local.acl.app # "system"
    owner   = local.acl.owner # "nobody"
    sharing = local.acl.sharing # "global"
    read    = local.acl.read # ["admin"]
    write   = local.acl.write # ["admin"]
  }
}
```

```
Error: Http Error: [400] 400 Bad Request {"messages":[{"type":"ERROR","text":"The following required arguments are missing: owner, sharing."}]}
```

Again, on the Splunk Cloud side, the following event exists, suggesting it is the same issue described above:

```
Custom REST endpoint at "/servicesNS/nobody/search/data/inputs/http/[HEC Endpoint Name]?count=-1&output_mode=json" was called by [REDACTED] with request data but no Content-Type: header; not parsing POST arguments
```

**Comment by YuanH** [comment]
Checking on this: is there a list of which resources are compatible with splunk cloud?
To me, the most important resources are: 
* `splunk_data_ui_views` 
* `splunk_saved_searches`

Both failed with "Post "https://<redacted>.splunkcloud.com:8089/servicesNS/bx-token-user/launcher/saved/searches?count=-1&output_mode=json": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"

**Comment by avishnyakov** [comment]
Hi team, this issue appears to be open for two years, since 2020
* how to manage Splunk alerts, dashboard at scale of hundreds and across multiple environments?
* how do other client deal with this? - by hand, or by writing automation on top of Splunk Cloud APIs?

Could you please recommend options here to manage hundreds of things at scale via codified workflows?
Next, what is ETA for cloud provider to be released?

**Comment by mausam-patel** [comment]
We are excited to announce the first release of the [Terraform Provider for Splunk Cloud](https://registry.terraform.io/providers/splunk/scp/latest) to allow automated, scalable configuration management for multiple Splunk Cloud deployments, hybrid use cases, and other services (such as AWS). The provider interacts with [ACS API](https://docs.splunk.com/Documentation/SplunkCloud/9.0.2209/Config/ACSIntro) endpoints and currently supports the Indexes resource for both Classic and Noah experiences. 


Documentation for resources supported by the provider, as well as troubleshooting and tips, can be found [here](https://registry.terraform.io/providers/splunk/scp/latest) and in the [Github Repo](https://github.com/splunk/terraform-provider-scp). As this is an iterative project, we request that you submit feature requests in the [Splunk Ideas](https://login.splunk.com/?redirecturl=https%3A%2F%2Flogin.splunk.com%2Fsso%2Fdispatch%3Ftype%3Daha%26fromURI%3Dhttps%253A%252F%252Fidp.login.splunk.com%252Fapp%252Fsplunkext_ideasaha_1%252Fexk7pkzsn9kR0rJHc2p7%252Fsso%252Fsaml%253FSAMLRequest%253DhZLNTuswEEZfJTuvEidpSm%25252BtplJFhSiCK1R%25252BFmyqqTOhVhzbeBxu4elJUxDcBbDxwjpzvk9jzwha7cSiCzuzxqcOKUQLIvRBWXNqDXUt%25252Bhv0z0ri3fqyZLsQHAnOyenONKpCoOR4wg4SZTn0Kn6wcglab0E2LFr2WmXg4Pw0qMol2j4qkxxdibQtB%25252Bfe1bgPm0HcezcZx30zcc0rmWmzTv3FuczdhBPZIYpFq2XJNvW2Oqkm0zSWW%25252FgTF1vM42k1zuPiZDyGoi5GaV33KFGHK0MBTChZnuajOM3jvLjNpmI0Eln2wKJ79DSUzZOURftWGxKHoJJ13ggLpEgYaJFEkOJmcXUpelDAx%25252BK%25252BjrifZ5y3wUqr2Xx2oMXQzs9%25252FXfOMf8Vnx2f82%25252BtXy2urlXyJFlrbf6ceIWDJgu%25252BQRWfWtxC%25252BL5Ql2XCjqrgeUNEZcihVrbBifH4M%25252Ff%25252B7zN8A) portal under Enterprise Cloud, and report any issues with the provider on our repo in Github. We will continue to add support for new resources, as well as update existing resources to work towards a mature, stable provider for Splunk Cloud Platform.
