### ISSUE TITLE
BUG: splunk_data_ui_views crashes with Could not find object id

### ISSUE THREAD

**Issue by stefmorren** [splunk/terraform-provider-splunk#143]
## Description
There seems to be a bug when deploying a dashboard through the Terraform provider. This makes it impossible to create any dashboards through the Splunk Provider.

I am using version 1.4.17.

## Error
`Error: Could not find object id=Terraform_Test_Dashboard`

## Steps to reproduce

1. Copy the sample code from https://registry.terraform.io/providers/splunk/splunk/latest/docs/resources/data_ui_views
2. Deploy it
3. It will crash during the apply phase.

**Comment by anushjay** [comment]
@stefmorren What version of Splunk are you trying to apply this configuration?

**Comment by anushjay** [comment]
@stefmorren I don't see the provider crashing. The provided example seems to be failing due to an invalid expression.

> Error: Invalid expression
> 
>   on main.tf line 34, in resource "splunk_data_ui_views" "dashboard":
>   34:   eai_data = <
> 
> Expected the start of an expression, but found an invalid expression token.

Fixed the example. The `examples/splunk/basic` uses the same example to create a dashboard and I have seen no issues. Closing this issue please for now, please reopen if you find any problems.
