### ISSUE TITLE
New version of Splunk provider errors with "a bool is required"

### ISSUE THREAD

**Issue by shubb30** [splunk/terraform-provider-splunk#66]
We are using the Splunk provider to push `splunk_saved_searches` into our Splunk installation.
Everything was working fine until the 1.4.1 version, and now my plan returns the error:

```
Error: a bool is required
```

Reverting back to 1.4.0 via versions.tf makes it start working again.

Our provider config:

```
provider "splunk" {
  insecure_skip_verify = true
  password = module.vault_tf.secrets.data.password
  url = module.vault_tf.secrets.data.address
  username = module.vault_tf.secrets.data.username
}
```

**Comment by anushjay** [comment]
Hi @shubb30 
The issue is due to a recent change in `1.4.1`. The data type for `alert_track` parameter in `saved_searches` resource was changed from string to bool. We will try to fix it by adding a proper state migration so you don't have deal with it manually.

In the meantime, you can remove state and import resource to use the latest version.
`terraform state rm splunk_saved_searches.<ID>`
`terraform import splunk_saved_searches.<ID> <NAME>`

**Comment by anushjay** [comment]
@shubb30 
running `terraform refresh` with `v1.4.3` of the provider should migrate the data type changes and resolve your issue.
